references: &golang-image
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/golem
version: 2
jobs:
  download_go_modules:
    <<: *golang-image
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  tests:
    <<: *golang-image
    steps:
        - checkout
        - run:
            name: Run golint
            command: >
                go get -u golang.org/x/lint/golint && golint ./...
        - run:
            name: Run vet
            command: go vet ./...
        - run:
            name: Run tests
            command: go test -v ./...

workflows:
    version: 2
    build_and_tests:
      jobs:
        - download_go_modules
        - tests:
            requires:
              - download_go_modules
